# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nitishsharma/localization-generation

pr: none

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
  - repository: self
    type: git
    ref: nitishsharma/localization-generation

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    fetchTags: true
  - task: cesve.one-loc-build.one-loc-build.OneLocBuild@2
    displayName: 'Localization Build: src/LocProject.json'
    inputs:
      locProj: src/LocProject.json
      isCreatePrSelected: true
      repoType: gitHub
      gitHubPatVariable: $(githubPatToken)
      isAutoCompletePrSelected: false
      packageSourceAuth: patAuth
      patVariable: $(OneLocBuildPat)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
