trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - src/l10n/l10n.xlf
    - src/loc

pr: none

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: localization
  displayName: localization
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: true
  - task: cesve.one-loc-build.one-loc-build.OneLocBuild@2
    displayName: 'Localization Build: src/LocProject.json'
    inputs:
      locProj: src/LocProject.json
      isCreatePrSelected: true
      repoType: gitHub
      gitHubPatVariable: $(githubPatToken)
      isAutoCompletePrSelected: false
      packageSourceAuth: patAuth
      dependencyPackageSource: 'https://msdata.pkgs.visualstudio.com/5603b9e3-ece0-4518-b9c8-1a36054d9970/_packaging/azuredatastudio-mysql-localization/nuget/v3/index.json'
  - task: ManifestGeneratorTask@0
    inputs:
      BuildDropPath: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
